name: Build HAQuDA
run-name: ${{ github.actor }} is building HAQuDA 🔨
on: [push, pull_request]
jobs:
  Build:
    strategy:
      matrix:
        name: ["esp32"]
        arch: ["esp32"]
        board: ["esp32"]
        opts: ["PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=error"]
        ssid: ["actions_ssid"]
        pass: ["actions_pass"]
        dns_domain: ["actions_domain"]
        dns_token: ["actions_token"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install core
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.name }}:${{ matrix.arch }}
          pip install pyserial
      - name: Print github actions vars
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          arduino-cli --help
          arduino-cli config dump
      - name: Compile Sketch
        working-directory: ./Software/Software_ver_2/
        run: ARDUINO_DIRECTORIES_USER=$GITHUB_WORKSPACE/Software/Software_ver_2/HAQuDA_Esp32 arduino-cli compile --fqbn ${{ matrix.name }}:${{ matrix.arch }}:${{ matrix.board }}:${{ matrix.opts }} --libraries Libs --library sketches --build-property=compiler.cpp.extra_flags="-DAP_SSID=${{ matrix.ssid }} -DAP_PASS=${{ matrix.pass }} -DDDNS_DOMAIN=${{ matrix.dns_domain }} -DDDNS_TOKEN=${{ matrix.dns_token }}" --verbose --clean --output-dir output